[features]
seeds = false
skip-lint = false
[programs.localnet]
onchain_voting = "AMbx16jhMdsJ9k2GvmaL3SXBkS7hD1nYUsHyRCYSxWUt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
